# compose.yaml

services:
  runner:
    build: 
      context: .
      target: runner
      tags: 
        - "hmmr:latest"
    volumes:
      - type: bind
        source: $HOME/data/preprocessed/HMMR
        target: /data
        bind:
          selinux: Z

  runner-all-methods:
    build: 
      context: .
      target: runner_all_methods
      tags: 
        - "hmmr-all-methods:latest"
    volumes:
      - type: bind
        source: $HOME/data/preprocessed/HMMR
        target: /data
        bind:
          selinux: Z
  runner-sample_size:
    build: 
      context: .
      target: runner_sample_size
      tags: 
        - "hmmr-sample_size:latest"
    volumes:
      - type: bind
        source: $HOME/data/preprocessed/HMMR
        target: /data
        bind:
          selinux: Z
  runner-node-spacing:
    build: 
      context: .
      target: runner_node_spacing
      tags: 
        - "hmmr-node-spacing:latest"
    volumes:
      - type: bind
        source: $HOME/data/preprocessed/HMMR
        target: /data
        bind:
          selinux: Z
  dev:
    build: 
      context: .
      target: dev
      tags: 
        - "hmmr:dev"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: $HOME/data/preprocessed/HMMR
        target: /data
        bind:
          selinux: Z
      - type: bind
        source: .
        target: /code
        bind:
          selinux: Z
